apiVersion: v1
baseDomain: futuregen-ocp4.lab
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: 0 
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: 3 
metadata:
  name: t1
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
fips: false 
pullSecret: '{"auths":{"registry.t1.futuregen.co.kr:5000": {"auth": "YWRtaW46YWRtaW4=","email": "dongsu.lee@futuregen.co.kr"}}}' 
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD3kLeItj8PW/sZkcmzVNVqgwsvev+leeXZu49JPjMejDuKQoiwfGZN7Z1AQRv1iLtLi39qObXeURBGUjnRbHPfIafCrR1zyWWgYy4GfR8vkTppZvIhh7i/DbBjHuRf5fwnvXJ4dYKbmiBdB9vyZNYyPEGw0N+VydhOuEtvWoScb5ts+0GPrOEvqvTBHFzOYw8pS+n9G4QLD+5RA3qjJ5VFjacA3Oczb7izyUo2qUw71hAtuKOvkDPSiJ/pshE1NuBySzWAN/ph9Ch+mpRprjOoO3bFbTpmgWVpH36lwHaaFYkr1mkMMtHY1DVmCI2RzU4llEMY7RDJ2z5zAf5JRcSd core@dslee-ocp4-monday.futuregen-ocp4.lab' 
additionalTrustBundle: | 
  -----BEGIN CERTIFICATE-----
  MIIFqTCCA5GgAwIBAgIJAMIa2RGwfJaBMA0GCSqGSIb3DQEBCwUAMGsxCzAJBgNV BAYTAlhYMRUwEwYDVQQHDAxEZWZhdWx0IENpdHkxHDAaBgNVBAoME0RlZmF1bHQg Q29tcGFueSBMdGQxJzAlBgNVBAMMHnJlZ2lzdHJ5LnQxLmZ1dHVyZWdlbi1vY3A0 LmxhYjAeFw0yMDAyMDEwMTI3MjlaFw0yMTAxMzEwMTI3MjlaMGsxCzAJBgNVBAYT AlhYMRUwEwYDVQQHDAxEZWZhdWx0IENpdHkxHDAaBgNVBAoME0RlZmF1bHQgQ29t cGFueSBMdGQxJzAlBgNVBAMMHnJlZ2lzdHJ5LnQxLmZ1dHVyZWdlbi1vY3A0Lmxh YjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMW7DutTjtk4gZZVke2f 7MpwXLSiq6NczSLRdj1x2JOsdqwlvBzSsAvRbB15zduIQMkMo/fSBQqVko1WMV3e 5C9zNtqWHolBuGXfYrB8P8Cc3Dz+Qg2jaWC6WjV15rpHWt371es/nZxeRu0/jzbR z69xehuRHVA9hKlWtrl+67wRbA6oKdS4ifvXRMgDJE8zYe+qiGevDip1kNZZqRFt 99kDLGmBfeRhmqkjjUA9uVhWh6E/SImergQ2+nzVNgs/wJyt+YF1kmlMJeE0gWP1 p+uZ7qWxy+RN5TWeSkJmNo1teuV4WlN7KWCoUN90d//1k0Fb7kIo6+7lBOT+H018 Tq3ud91EPRbhMZxFEZepUw1D8nYnQQm6laP7zJWMitfihcVyXiklqGOxFUTqvstP FGNLeIDY5iJlS3EanUoZnO9Tf6UgdIatJ1dVfKOXGiBA/yuCIzpO0iPUXkATAYvo ifBMZjjH/nD5oNFay2FsU3VH7ll67z9n5reOfTDqS0xDpgZw3Juypono1xnyjY7w 2Kyfr9LSKzuUkfTYIPmA44wk1hxjB+nvH1gEJ4Ayvv2Mphw7+Cdvnh1R5E0GWiUE xAem2Xe3Q1JrDU5dBPPm8gZKU+/pu6usQxzFI2HDNIyfqyPsljGAv5XIOa7q8HKo M0eYbC4eTY3FD2PxcUsNR8jnAgMBAAGjUDBOMB0GA1UdDgQWBBSfT+ICwLTJB1am wPc/lo8PPYlnajAfBgNVHSMEGDAWgBSfT+ICwLTJB1amwPc/lo8PPYlnajAMBgNV HRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQAHDjx59HPUxA1vzOjk3gdJe++r AUOz1SM1JLp8gubHVdUKD3ujDt9LNc2oHB3nZPz45hr0ZY7pYvVNSWHx6w6XDymd hBbf94kgGVkG++DZVYR42PR+ZPJj+JZ29f3rQScrKzWjHTxWUDP1Kh9dHGp427kL v09s2FlQgwof5eoIiDz/2RwCWmt+a4aY56spDX0m+VNE8gOio6VwBanMMrHl8MXI Mup+NeXl+etG55cTGaBjNpSsnfY014w0/cQEv3+oiJwc2DCMT4BM8hMcW2l0NH9w /jCTTx7czY+aEePjQ5iG2icu89M4gYJz2WctfXC2cqmE1E4SBSjpsivi8H495LhN CSUV3SB1JagE8twoUMSXaR5+39WEF6LdflvZWqMHT27pyeRrXIbbtwhwBhWhl5JD Z63Itp7hLv3D6DM8LYFKk1bNGTaOhr1LniV6LFpEuavbd0dgpVCWHRhTu7bZfMsO xzVak4fQeTY8kZV+eGaNf0hjQ4hvjyqh5iI/muKEVX6rSWykhKoDaKvTRliA1NyA U7wVnk9gRXovJNsJO2YcaO1Zw5Up1vH3yQ17zhsJKs8sh9VMLKSoNLnaWRYg299a R+u2MR89w6iPNeUJgnwHmqKSZ68IcbFQFg54xHXR6NzE1f15IEOpoI6PDo7LbTLK G7vZ9sbVlP4nOH7E0g==
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - registry.t1.futuregen-ocp4.lab:5000/ocp4/openshift4/release
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.t1.futuregen-ocp4.lab:5000/ocp4/openshift4/release
  source: registry.svc.ci.openshift.org/ocp/release

